In [38]:
#Run First Time Only To Install Packages and Restart Kernel
%pip install openmdao[doe]
%pip install pyDOE3
%pip install kaleido
#I've had to add the following lines for some reason, possibly because I have a conda install setup elsewhere? But that doesn't really make a lot of sense. 
%pip install matplotlib
%pip install requests-cache
%pip install openmeteo-requests
%pip install retry_requests
%pip install orbit-nrel
%pip install rich
%pip install wombat
%pip install CoolProp
%pip install ruamel.yaml
%pip install numpy_financial
%pip install pandas
%pip install dill
%pip install ProFAST
%pip install floris
%pip install nrel-pysam
%pip install hopp
%pip install geopy

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you 

In [42]:
# from h2integrate.core.h2integrate_model import H2IntegrateModel
#from inl_h2integrate.h2integrate.core.h2integrate_model import H2IntegrateModel
from h2integrate.core.h2integrate_model import H2IntegrateModel
# Create a GreenHEART model
h2i = H2IntegrateModel("examples/29_nuclear_reactor/nuclear_reactor_htse_lte.yaml")

# Run the model
h2i.run()

h2i.post_process()

print("Success!")

Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|0
---------------------------------------------------------------
Design Vars
{'electrolyzer.n_clusters': array([25.]),
 'nuclear.hourly_hydrogen_production': array([10.]),
 'nuclear.hourly_power_production': array([500.])}

Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([32.30665712])}

Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|1
---------------------------------------------------------------
Design Vars
{'electrolyzer.n_clusters': array([25.]),
 'nuclear.hourly_hydrogen_production': array([10.]),
 'nuclear.hourly_power_production': array([500.])}

Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([32.30665712])}


Initialization step with radius = 0.1
Number of function values = 0   Least value of F = 32.30665712010124   Constraint violation = 0.0
The corresponding X is:
[ 25. 500.  10.]
The 

53 explicit inputs:

╷                   ╷           ╷       ╷                                     
 Variable                            │              Mean │ Units     │ Shape │ Promoted name                       
╶────────────────────────────────────┼───────────────────┼───────────┼───────┼────────────────────────────────────╴
 plant                               │                   │           │       │                                     
   combiner                          │                   │           │       │                                     
     combiner_performance            │                   │           │       │                                     
       hydrogen_in1                  │          100,000. │ kg/h      │ 8760  │ combiner.hydrogen_in1               
       hydrogen_in2                  │           778.824 │ kg/h      │ 8760  │ combiner.hydrogen_in2               
   electrolyzer                      │                   │           │       │                                     
     eco_pem_electrolyzer_performanc │                   │           │       │                                     
 e                                   │                   │           │       │                                     
       electricity_in                │       40,146.1087 │ kW        │ 8760  │ electrolyzer.electricity_in         
     singlitico_electrolyzer_cost    │                   │           │       │                                     
       electricity_in                │       40,146.1087 │ kW        │ 8760  │ electrolyzer.electricity_in         
       n_clusters                    │               40. │ unitless  │ 1     │ electrolyzer.n_clusters             
       cluster_size                  │               -1. │ MW        │ 1     │ electrolyzer.cluster_size           
       max_hydrogen_capacity         │            1,000. │ kg/h      │ 1     │ electrolyzer.max_hydrogen_capacity  
       size_mode                     │               n/a │ n/a       │ n/a   │ electrolyzer.size_mode              
       total_hydrogen_produced       │      6,481,116.41 │ kg/year   │ 1     │ electrolyzer.total_hydrogen_produce 
                                     │                   │           │       │ d                                   
       electrolyzer_size_mw          │               40. │ MW        │ 1     │ electrolyzer.electrolyzer_size_mw   
   electrolyzer_to_combiner_pipe     │                   │           │       │                                     
     hydrogen_in                     │            0.2163 │ kg/s      │ 8760  │ electrolyzer_to_combiner_pipe.hydro 
                                     │                   │           │       │ gen_in                              
   finance_subgroup_electricity      │                   │           │       │                                     
     adjusted_capex_opex_comp        │                   │           │       │                                     
       capex_nuclear                 │   30,000,000,000. │ USD       │ 1     │ finance_subgroup_electricity.capex_ 
                                     │                   │           │       │ nuclear                             
       opex_nuclear                  │     12,110,079.47 │ USD/year  │ 1     │ finance_subgroup_electricity.opex_n 
                                     │                   │           │       │ uclear                              
       varopex_nuclear               │                0. │ USD/year  │ 30    │ finance_subgroup_electricity.varope 
                                     │                   │           │       │ x_nuclear                           
       cost_year_nuclear             │            2,025. │ n/a       │ n/a   │ finance_subgroup_electricity.cost_y 
                                     │                   │           │       │ ear_nuclear                         
     electricity_finance_profast_mod │                   │           │       │               

63 explicit outputs:

╷                   ╷           ╷       ╷                                     
 Variable                            │              Mean │ Units     │ Shape │ Promoted name                       
╶────────────────────────────────────┼───────────────────┼───────────┼───────┼────────────────────────────────────╴
 plant                               │                   │           │       │                                     
   combiner                          │                   │           │       │                                     
     combiner_performance            │                   │           │       │                                     
       hydrogen_out                  │        100,778.82 │ kg/h      │ 8760  │ combiner.hydrogen_out               
     pyomo_dispatch_generic_converte │                   │           │       │                                     
 r                                   │                   │           │       │                                     
       dispatch_block_rule_function  │               n/a │ n/a       │ n/a   │ combiner.dispatch_block_rule_functi 
                                     │                   │           │       │ on                                  
   electrolyzer                      │                   │           │       │                                     
     eco_pem_electrolyzer_performanc │                   │           │       │                                     
 e                                   │                   │           │       │                                     
       hydrogen_out                  │           778.824 │ kg/h      │ 8760  │ electrolyzer.hydrogen_out           
       time_until_replacement        │       80,003.2476 │ h         │ 1     │ electrolyzer.time_until_replacement 
       total_hydrogen_produced       │      6,481,116.41 │ kg/year   │ 1     │ electrolyzer.total_hydrogen_produce 
                                     │                   │           │       │ d                                   
       efficiency                    │            0.7645 │ n/a       │ 1     │ electrolyzer.efficiency             
       rated_h2_production_kg_pr_hr  │          784.3545 │ kg/h      │ 1     │ electrolyzer.rated_h2_production_kg 
                                     │                   │           │       │ _pr_hr                              
       electrolyzer_size_mw          │               40. │ MW        │ 1     │ electrolyzer.electrolyzer_size_mw   
       hydrogen_capacity_factor      │            0.9433 │ unitless  │ 1     │ electrolyzer.hydrogen_capacity_fact 
                                     │                   │           │       │ or                                  
     singlitico_electrolyzer_cost    │                   │           │       │                                     
       CapEx                         │     42,662,014.69 │ USD       │ 1     │ electrolyzer.CapEx                  
       OpEx                          │      1,118,218.25 │ USD/year  │ 1     │ electrolyzer.OpEx                   
       VarOpEx                       │                0. │ USD/year  │ 30    │ electrolyzer.VarOpEx                
       cost_year                     │              2021 │ n/a       │ n/a   │ electrolyzer.cost_year              
   electrolyzer_to_combiner_pipe     │                   │           │       │                                     
     hydrogen_out                    │            0.2163 │ kg/s      │ 8760  │ electrolyzer_to_combiner_pipe.hydro 
                                     │                   │           │       │ gen_out                             
   finance_subgroup_electricity      │                   │           │       │                                     
     adjusted_capex_opex_comp        │                   │           │       │                                     
       capex_adjusted_nuclear        │ 27,857,982,327.59 │ USD       │ 1     │ finance_subgro

Success!


In [43]:
nuclear_elec_out = h2i.prob.get_val("nuclear.electricity_out", units='MW')
nuclear_elec_out

array([40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14610867,
       40.14610867, 40.14610867, 40.14610867, 40.14610867, 40.14

In [47]:
nuclear_h2_out = h2i.prob.get_val("nuclear.hydrogen_out", units='kg/h')
nuclear_h2_out

array([100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 100000., 100000., 100000., 100000., 100000., 100000.,
       100000., 1000

In [48]:
electrolyzer_h2_out = h2i.prob.get_val("electrolyzer.hydrogen_out", units='kg/h')
electrolyzer_h2_out

array([784.35319909, 784.35192462, 784.35065016, 784.3493757 ,
       784.34810124, 784.34682679, 784.34555234, 784.3442779 ,
       784.34300346, 784.34172902, 784.34045459, 784.33918016,
       784.33790574, 784.33663132, 784.3353569 , 784.33408249,
       784.33280809, 784.33153368, 784.33025928, 784.32898489,
       784.3277105 , 784.32643611, 784.32516173, 784.32388735,
       784.32261298, 784.32133861, 784.32006424, 784.31878988,
       784.31751553, 784.31624117, 784.31496682, 784.31369248,
       784.31241814, 784.3111438 , 784.30986947, 784.30859514,
       784.30732082, 784.3060465 , 784.30477218, 784.30349787,
       784.30222356, 784.30094926, 784.29967496, 784.29840066,
       784.29712637, 784.29585209, 784.2945778 , 784.29330353,
       784.29202925, 784.29075498, 784.28948071, 784.28820645,
       784.28693219, 784.28565794, 784.28438369, 784.28310945,
       784.2818352 , 784.28056097, 784.27928673, 784.27801251,
       784.27673828, 784.27546406, 784.27418984, 784.27

In [49]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import kaleido
import os 
def plot_graph(x_data, y_data, line_name, title, x_title, y_title, filename, line_color, y, fig_show = False):
    # Define the figure
    fig = make_subplots(specs=[[{"secondary_y": True}]]) # fig = go.Figure()
    # Add data to figure
    for i in range(0, len(x_data), 1):
        fig.add_trace(go.Scatter(x=x_data[i], y=y_data[i], name= line_name[i], line_color = line_color[i], yaxis = y[i]))
            
    # Create Layout for the Html
    
    fig.update_layout(
        title=go.layout.Title(
            text= title,
            xref="paper",
            x=0.5
        ),
        xaxis=go.layout.XAxis(
            title=go.layout.xaxis.Title(
                text=x_title,
            ),
            rangeslider=dict(
                visible=True
            )
        )
    )

    fig.update_layout(
    xaxis=dict(
        domain=[0.05, 0.95]
    ),
    yaxis=dict(
        title=dict(
            text="Power (kW)"
        )
    ),
    yaxis2=dict(
        title=dict(
            text="Hydrogen Produced (kg/h)"
        ),
        overlaying="y",
        side="right"
    ),
    yaxis3=dict(
        title=dict(
            text="yaxis3 title"
        ),
        anchor="free",
        overlaying="y",
        autoshift=True
    ),
    yaxis4=dict(
        title=dict(
            text="yaxis4 title"
        ),
        anchor="free",
        overlaying="y",
        autoshift=True
    ))
    
    fig.write_html((filename + '.html'), include_mathjax='cdn')
    fig.write_image(filename + '.svg')
    fig.write_image(filename + '.pdf')
    if fig_show:
        fig.show()

In [51]:
os.chdir(r"C:\Users\MIKKDM\Documents\H2Integrate\inl_h2integrate\examples\29_nuclear_reactor")
x_title = "Time"
y_title = ["Power (MW)", "Hydrogen Produced (kg/h)"]
line_name = ["Electricity Out", "Hydrogen Produced"]
line_color = ["deepskyblue", "red"]
x_data = [np.arange(8760)] * 2
y_data = [nuclear_elec_out, electrolyzer_h2_out]
title = "Nuclear Reactor Optimization Output"
filename = "nuclear_example_output"
y = ["y1", "y2"]
plot_graph(x_data, y_data, line_name, title, x_title, y_title, filename, line_color, y)

