In [21]:
#Run First Time Only To Install Packages and Restart Kernel
#%pip install openmdao[doe]
#%pip install pyDOE3
%pip install kaleido
#I've had to add the following lines for some reason, possibly because I have a conda install setup elsewhere? But that doesn't really make a lot of sense. 
#%pip install matplotlib
#%pip install requests-cache
#%pip install openmeteo-requests
#%pip install retry_requests
#%pip install orbit-nrel
#%pip install rich
#%pip install wombat
#%pip install CoolProp
#%pip install ruamel.yaml
#%pip install numpy_financial
#%pip install pandas
#%pip install dill
#%pip install ProFAST
#%pip install floris
#%pip install nrel-pysam
#%pip install hopp
#%pip install geopy

Note: you may need to restart the kernel to use updated packages.


In [6]:
from h2integrate.core.h2integrate_model import H2IntegrateModel

h2i = H2IntegrateModel("nuclear_reactor_thermal_htse.yaml")

h2i.run()

h2i.post_process()

print("Success!")

Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|0
---------------------------------------------------------------
Design Vars
{'htse.n_clusters': array([25.]),
 'nuclear.hourly_power_production': array([500.])}

Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([0.53081342])}

Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|1
---------------------------------------------------------------
Design Vars
{'htse.n_clusters': array([25.]),
 'nuclear.hourly_power_production': array([500.])}

Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([0.53081342])}


Initialization step with radius = 0.1
Number of function values = 0   Least value of F = 0.5308134231211967   Constraint violation = 0.0
The corresponding X is: [500.  25.]
The constraint value is:
[-499.  -23.    0.  -15.]
Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|2
-----------------

54 explicit inputs:

╷                   ╷             ╷       ╷                                    
 Variable                           │              Mean │ Units       │ Shape │ Promoted name                      
╶───────────────────────────────────┼───────────────────┼─────────────┼───────┼───────────────────────────────────╴
 plant                              │                   │             │       │                                    
   combiner                         │                   │             │       │                                    
     GenericCombinerPerformanceMode │                   │             │       │                                    
 l                                  │                   │             │       │                                    
       hydrogen_in1                 │                0. │ kg/h        │ 8760  │ combiner.hydrogen_in1              
       rated_hydrogen_production1   │                0. │ kg/h        │ 1     │ combiner.rated_hydrogen_production 
                                    │                   │             │       │ 1                                  
       hydrogen_capacity_factor1    │                0. │ unitless    │ 30    │ combiner.hydrogen_capacity_factor1 
       hydrogen_in2                 │                0. │ kg/h        │ 8760  │ combiner.hydrogen_in2              
       rated_hydrogen_production2   │                0. │ kg/h        │ 1     │ combiner.rated_hydrogen_production 
                                    │                   │             │       │ 2                                  
       hydrogen_capacity_factor2    │                0. │ unitless    │ 30    │ combiner.hydrogen_capacity_factor2 
   finance_subgroup_electricity     │                   │             │       │                                    
     adjusted_capex_opex_comp       │                   │             │       │                                    
       capex_nuclear                │   28,750,000,000. │ USD         │ 1     │ finance_subgroup_electricity.capex 
                                    │                   │             │       │ _nuclear                           
       opex_nuclear                 │       13,200,000. │ USD/year    │ 1     │ finance_subgroup_electricity.opex_ 
                                    │                   │             │       │ nuclear                            
       varopex_nuclear              │       39,833,472. │ USD/year    │ 30    │ finance_subgroup_electricity.varop 
                                    │                   │             │       │ ex_nuclear                         
       cost_year_nuclear            │            2,025. │ n/a         │ n/a   │ finance_subgroup_electricity.cost_ 
                                    │                   │             │       │ year_nuclear                       
     electricity_finance_profast_mo │                   │             │       │                                    
 del                                │                   │             │       │                                    
       rated_electricity_production │          313,600. │ kW          │ 1     │ finance_subgroup_electricity.rated 
                                    │                   │             │       │ _electricity_production            
       capacity_factor              │                1. │ unitless    │ 30    │ finance_subgroup_electricity.capac 
                                    │                   │             │       │ ity_factor                         
       capex_adjusted_nuclear       │ 26,697,233,063.94 │ USD         │ 1     │ finance_subgroup_electricity.capex 
                                    │                   │             │       │ _adjusted_nuclear                  
       opex_adjusted_nuclear        │     12,257,512.22 │ USD/year    │ 1     │ finance_subgroup_electricity.opex_ 
                                    │                   │             │       │ adjusted_nuc

82 explicit outputs:

╷                   ╷           ╷       ╷                                     
 Variable                            │              Mean │ Units     │ Shape │ Promoted name                       
╶────────────────────────────────────┼───────────────────┼───────────┼───────┼────────────────────────────────────╴
 plant                               │                   │           │       │                                     
   combiner                          │                   │           │       │                                     
     GenericCombinerPerformanceModel │                   │           │       │                                     
       hydrogen_out                  │                0. │ kg/h      │ 8760  │ combiner.hydrogen_out               
       capacity_factor               │                0. │ unitless  │ 30    │ combiner.capacity_factor            
       rated_hydrogen_production     │                0. │ kg/h      │ 1     │ combiner.rated_hydrogen_production  
   finance_subgroup_electricity      │                   │           │       │                                     
     adjusted_capex_opex_comp        │                   │           │       │                                     
       capex_adjusted_nuclear        │ 26,697,233,063.94 │ USD       │ 1     │ finance_subgroup_electricity.capex_ 
                                     │                   │           │       │ adjusted_nuclear                    
       opex_adjusted_nuclear         │     12,257,512.22 │ USD/year  │ 1     │ finance_subgroup_electricity.opex_a 
                                     │                   │           │       │ djusted_nuclear                     
       varopex_adjusted_nuclear      │     36,989,338.63 │ USD/year  │ 30    │ finance_subgroup_electricity.varope 
                                     │                   │           │       │ x_adjusted_nuclear                  
       total_capex_adjusted          │ 26,697,233,063.94 │ USD       │ 1     │ finance_subgroup_electricity.total_ 
                                     │                   │           │       │ capex_adjusted                      
       total_opex_adjusted           │     12,257,512.22 │ USD/year  │ 1     │ finance_subgroup_electricity.total_ 
                                     │                   │           │       │ opex_adjusted                       
       total_varopex_adjusted        │     36,989,338.63 │ USD/year  │ 30    │ finance_subgroup_electricity.total_ 
                                     │                   │           │       │ varopex_adjusted                    
     electricity_finance_profast_mod │                   │           │       │                                     
 el                                  │                   │           │       │                                     
       LCOE                          │            1.0407 │ USD/kW/h  │ 1     │ finance_subgroup_electricity.LCOE   
       wacc_electricity              │            0.0625 │ percent   │ 1     │ finance_subgroup_electricity.wacc_e 
                                     │                   │           │       │ lectricity                          
       crf_electricity               │            0.0723 │ percent   │ 1     │ finance_subgroup_electricity.crf_el 
                                     │                   │           │       │ ectricity                           
       irr_electricity               │              0.09 │ percent   │ 1     │ finance_subgroup_electricity.irr_el 
                                     │                   │           │       │ ectricity                           
       profit_index_electricity      │            1.5542 │ unitless  │ 1     │ finance_subgroup_electricity.profit 
                                     │                   │           │       │ _index_electricity                  
       investor_payback_period_elect │                 8 │ year      │ 1     │ finance_subgro

Success!


# from h2integrate.core.h2integrate_model import H2IntegrateModel
#from inl_h2integrate.h2integrate.core.h2integrate_model import H2IntegrateModel
from h2integrate.core.h2integrate_model import H2IntegrateModel
# Create a GreenHEART model
h2i = H2IntegrateModel("nuclear_reactor_thermal_htse.yaml")

# Run the model
h2i.run()

h2i.post_process()

print("Success!")

In [19]:
nuclear_elec_out = h2i.prob.get_val("nuclear.electricity_out", units='kW')
nuclear_elec_out

array([313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 313600., 313600., 313600., 313600., 313600., 313600.,
       313600., 3136

In [18]:
nuclear_h2_out = h2i.prob.get_val("nuclear.high_pressure_heat", units='kW')
nuclear_h2_out

array([1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 1000000.,
       1000000., 1000000., 1000000., 1000000., 1000000., 10000

In [24]:
nuclear_h2_out = h2i.prob.get_val("htse.electricity_demand", units='kW')
nuclear_h2_out

array([30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
       30521.73913043, 30521.73913043, 30521.73913043, 30521.73913043,
      

In [9]:
electrolyzer_h2_out = h2i.prob.get_val("htse.hydrogen_out", units='kg/h')
electrolyzer_h2_out

array([706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52

In [23]:
rated_h2_prod = h2i.prob.get_val("htse.nominal_electricity_required")
rated_h2_prod

KeyError: ": Variable 'htse.nominal_electricity_required' not found. Perhaps you meant one of the following variables: ['htse.electricity_demand', 'htse.electricity_in', 'nuclear.total_electricity_produced']."

In [11]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
#import kaleido
import os 
def plot_graph(x_data, y_data, line_name, title, x_title, y_title, filename, line_color, y, fig_show = False):
    # Define the figure
    fig = make_subplots(specs=[[{"secondary_y": True}]]) # fig = go.Figure()
    # Add data to figure
    for i in range(0, len(x_data), 1):
        fig.add_trace(go.Scatter(x=x_data[i], y=y_data[i], name= line_name[i], line_color = line_color[i], yaxis = y[i]))
            
    # Create Layout for the Html
    
    fig.update_layout(
        title=go.layout.Title(
            text= title,
            xref="paper",
            x=0.5
        ),
        xaxis=go.layout.XAxis(
            title=go.layout.xaxis.Title(
                text=x_title,
            ),
            rangeslider=dict(
                visible=True
            )
        )
    )

    fig.update_layout(
    xaxis=dict(
        domain=[0.05, 0.95]
    ),
    yaxis=dict(
        title=dict(
            text="Power (kW)"
        )
    ),
    yaxis2=dict(
        title=dict(
            text="Hydrogen Produced (kg/h)"
        ),
        overlaying="y",
        side="right"
    ),
    yaxis3=dict(
        title=dict(
            text="yaxis3 title"
        ),
        anchor="free",
        overlaying="y",
        autoshift=True
    ),
    yaxis4=dict(
        title=dict(
            text="yaxis4 title"
        ),
        anchor="free",
        overlaying="y",
        autoshift=True
    ))
    
    fig.write_html((filename + '.html'), include_mathjax='cdn')
    fig.write_image(filename + '.svg')
    fig.write_image(filename + '.pdf')
    if fig_show:
        fig.show()

In [20]:
os.chdir(r"C:\Users\MIKKDM\Documents\H2Integrate\NucH2INtegrate\examples\99_nuclear_reactor_htse")

x_title = "Time"
y_title = ["Power (MW)", "Hydrogen Produced (kg/h)"]
line_name = ["Electricity Out", "Hydrogen Produced"]
line_color = ["deepskyblue", "red"]
x_data = [np.arange(8760)] * 2
y_data = [nuclear_elec_out, electrolyzer_h2_out]
title = "Nuclear Reactor Optimization Output"
filename = "nuclear_example_output"
y = ["y1", "y2"]
plot_graph(x_data, y_data, line_name, title, x_title, y_title, filename, line_color, y)

