In [ ]:
# Run First Time Only To Install Packages and Restart Kernel
# %pip install openmdao[doe]
# %pip install pyDOE3
%pip install kaleido
# I've had to add the following lines for some reason, possibly because I have a conda install
# setup elsewhere? But that doesn't really make a lot of sense.
# %pip install matplotlib
# %pip install requests-cache
# %pip install openmeteo-requests
# %pip install retry_requests
# %pip install orbit-nrel
# %pip install rich
# %pip install wombat
# %pip install CoolProp
# %pip install ruamel.yaml
# %pip install numpy_financial
# %pip install pandas
# %pip install dill
# %pip install ProFAST
# %pip install floris
# %pip install nrel-pysam
# %pip install hopp
# %pip install geopy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [kaleido]m4/5 [kaleido]
Note: you may need to restart the kernel to use updated packages.


In [2]:
from h2integrate.core.h2integrate_model import H2IntegrateModel

h2i = H2IntegrateModel("nuclear_reactor_thermal_htse.yaml")

h2i.run()

h2i.post_process()

print("Success!")

Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|0
---------------------------------------------------------------
Design Vars
{'htse.n_clusters': array([25.]),
 'nuclear.hourly_power_production': array([500.])}


=====
plant
=====
NL: NLBGSSolver 'NL: NLBGS' on system 'plant': residuals contain 'inf' or 'NaN' after 1 iterations.
Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([116.84595863])}

Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|1
---------------------------------------------------------------
Design Vars
{'htse.n_clusters': array([25.]),
 'nuclear.hourly_power_production': array([500.])}


=====
plant
=====
NL: NLBGSSolver 'NL: NLBGS' on system 'plant': residuals contain 'inf' or 'NaN' after 1 iterations.
Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([116.84595863])}


Initialization step with radius = 0.1
Number of function values

/Users/jthomas2/anaconda3/envs/h2integrate/lib/python3.11/site-packages/openmdao/utils/relevance.py:1296: OpenMDAOWarning:The following groups have a nonlinear solver that computes gradients and will be treated as atomic for the purposes of determining which systems are included in the optimization iteration: 
plant




=====
plant
=====
NL: NLBGSSolver 'NL: NLBGS' on system 'plant': residuals contain 'inf' or 'NaN' after 1 iterations.
Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([116.84595863])}


Initialization step with radius = 0.1
Number of function values = 1   Least value of F = 116.84595862793581   Constraint violation = 0.10000000000002274
The corresponding X is: [500.1  25. ]
The constraint value is:
[-4.991e+02 -2.300e+01  1.000e-01 -1.500e+01]
Driver debug print for iter coord: rank0:ScipyOptimize_COBYLA|3
---------------------------------------------------------------
Design Vars
{'htse.n_clusters': array([25.1]),
 'nuclear.hourly_power_production': array([500.])}


=====
plant
=====
NL: NLBGSSolver 'NL: NLBGS' on system 'plant': residuals contain 'inf' or 'NaN' after 1 iterations.
Nonlinear constraints
None

Linear constraints
None

Objectives
{'finance_subgroup_hydrogen.LCOH': array([112.3722992])}


Initialization step with r

64 explicit inputs:

╷                  ╷             ╷       ╷                                    
 Variable                            │             Mean │ Units       │ Shape │ Promoted name                      
╶────────────────────────────────────┼──────────────────┼─────────────┼───────┼───────────────────────────────────╴
 plant                               │                  │             │       │                                    
   combiner                          │                  │             │       │                                    
     GenericCombinerPerformanceModel │                  │             │       │                                    
       hydrogen_in1                  │               0. │ kg/h        │ 8760  │ combiner.hydrogen_in1              
       rated_hydrogen_production1    │               0. │ kg/h        │ 1     │ combiner.rated_hydrogen_production 
                                     │                  │             │       │ 1                                  
       hydrogen_capacity_factor1     │               0. │ unitless    │ 30    │ combiner.hydrogen_capacity_factor1 
       hydrogen_in2                  │               0. │ kg/h        │ 8760  │ combiner.hydrogen_in2              
       rated_hydrogen_production2    │               0. │ kg/h        │ 1     │ combiner.rated_hydrogen_production 
                                     │                  │             │       │ 2                                  
       hydrogen_capacity_factor2     │               0. │ unitless    │ 30    │ combiner.hydrogen_capacity_factor2 
   finance_subgroup_electricity      │                  │             │       │                                    
     adjusted_capex_opex_comp        │                  │             │       │                                    
       capex_nuclear                 │   5,750,000,000. │ USD         │ 1     │ finance_subgroup_electricity.capex 
                                     │                  │             │       │ _nuclear                           
       opex_nuclear                  │       2,640,000. │ USD/year    │ 1     │ finance_subgroup_electricity.opex_ 
                                     │                  │             │       │ nuclear                            
       varopex_nuclear               │    126,992,055.6 │ USD/year    │ 30    │ finance_subgroup_electricity.varop 
                                     │                  │             │       │ ex_nuclear                         
       cost_year_nuclear             │           2,025. │ n/a         │ n/a   │ finance_subgroup_electricity.cost_ 
                                     │                  │             │       │ year_nuclear                       
     electricity_finance_profast_mod │                  │             │       │                                    
 el                                  │                  │             │       │                                    
       rated_electricity_production  │       1,000,000. │ kW          │ 1     │ finance_subgroup_electricity.rated 
                                     │                  │             │       │ _electricity_production            
       capacity_factor               │           0.9998 │ unitless    │ 30    │ finance_subgroup_electricity.capac 
                                     │                  │             │       │ ity_factor                         
       capex_adjusted_nuclear        │ 5,339,446,612.79 │ USD         │ 1     │ finance_subgroup_electricity.capex 
                                     │                  │             │       │ _adjusted_nuclear                  
       opex_adjusted_nuclear         │     2,451,502.44 │ USD/year    │ 1     │ finance_subgroup_electricity.opex_ 
                                     │                  │             │       │ adjusted_nuclear                   
       varopex_adjusted_nuclear      │   117,924,748.02 │ USD/year    │ 30    │ finance_subgr

91 explicit outputs:

╷                  ╷           ╷       ╷                                      
 Variable                            │             Mean │ Units     │ Shape │ Promoted name                        
╶────────────────────────────────────┼──────────────────┼───────────┼───────┼─────────────────────────────────────╴
 plant                               │                  │           │       │                                      
   combiner                          │                  │           │       │                                      
     GenericCombinerPerformanceModel │                  │           │       │                                      
       hydrogen_out                  │               0. │ kg/h      │ 8760  │ combiner.hydrogen_out                
       capacity_factor               │               0. │ unitless  │ 30    │ combiner.capacity_factor             
       rated_hydrogen_production     │               0. │ kg/h      │ 1     │ combiner.rated_hydrogen_production   
   finance_subgroup_electricity      │                  │           │       │                                      
     adjusted_capex_opex_comp        │                  │           │       │                                      
       capex_adjusted_nuclear        │ 5,339,446,612.79 │ USD       │ 1     │ finance_subgroup_electricity.capex_a 
                                     │                  │           │       │ djusted_nuclear                      
       opex_adjusted_nuclear         │     2,451,502.44 │ USD/year  │ 1     │ finance_subgroup_electricity.opex_ad 
                                     │                  │           │       │ justed_nuclear                       
       varopex_adjusted_nuclear      │   117,924,748.02 │ USD/year  │ 30    │ finance_subgroup_electricity.varopex 
                                     │                  │           │       │ _adjusted_nuclear                    
       total_capex_adjusted          │ 5,339,446,612.79 │ USD       │ 1     │ finance_subgroup_electricity.total_c 
                                     │                  │           │       │ apex_adjusted                        
       total_opex_adjusted           │     2,451,502.44 │ USD/year  │ 1     │ finance_subgroup_electricity.total_o 
                                     │                  │           │       │ pex_adjusted                         
       total_varopex_adjusted        │   117,924,748.02 │ USD/year  │ 30    │ finance_subgroup_electricity.total_v 
                                     │                  │           │       │ aropex_adjusted                      
     electricity_finance_profast_mod │                  │           │       │                                      
 el                                  │                  │           │       │                                      
       LCOE                          │            0.079 │ USD/kW/h  │ 1     │ finance_subgroup_electricity.LCOE    
       wacc_electricity              │           0.0625 │ percent   │ 1     │ finance_subgroup_electricity.wacc_el 
                                     │                  │           │       │ ectricity                            
       crf_electricity               │           0.0723 │ percent   │ 1     │ finance_subgroup_electricity.crf_ele 
                                     │                  │           │       │ ctricity                             
       irr_electricity               │             0.09 │ percent   │ 1     │ finance_subgroup_electricity.irr_ele 
                                     │                  │           │       │ ctricity                             
       profit_index_electricity      │           1.5696 │ unitless  │ 1     │ finance_subgroup_electricity.profit_ 
                                     │                  │           │       │ index_electricity                    
       investor_payback_period_elect │                8 │ year      │ 1     │ finance_subgrou

Success!


# from h2integrate.core.h2integrate_model import H2IntegrateModel
#from inl_h2integrate.h2integrate.core.h2integrate_model import H2IntegrateModel
from h2integrate.core.h2integrate_model import H2IntegrateModel
# Create a GreenHEART model
h2i = H2IntegrateModel("nuclear_reactor_thermal_htse.yaml")

# Run the model
h2i.run()

h2i.post_process()

print("Success!")

In [3]:
nuclear_elec_out = h2i.prob.get_val("nuclear.electricity_out", units="kW")
nuclear_elec_out

array([999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 999780., 999780., 999780., 999780., 999780., 999780.,
       999780., 9997

In [4]:
nuclear_h2_out = h2i.prob.get_val("nuclear.heat_out", units="kW")
nuclear_h2_out

array([1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000.,

In [5]:
nuclear_h2_out = h2i.prob.get_val("htse.electricity_demand", units="kW")
nuclear_h2_out

array([29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
       29521.73913043, 29521.73913043, 29521.73913043, 29521.73913043,
      

In [6]:
electrolyzer_h2_out = h2i.prob.get_val("htse.hydrogen_out", units="kg/h")
electrolyzer_h2_out

array([706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52173913,
       706.52173913, 706.52173913, 706.52173913, 706.52

In [7]:
htse_heat_in = h2i.prob.get_val("htse.heat_in", units="kW")
htse_heat_in

array([1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.,
       1000., 1000.,

In [20]:
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# import kaleido


def plot_graph(
    x_data,
    y_data,
    line_name,
    title,
    x_title,
    y_title,
    filename,
    line_color,
    y,
    line_styles,
    fig_show=False,
):
    # Define the figure
    fig = make_subplots(specs=[[{"secondary_y": True}]])  # fig = go.Figure()
    # Add data to figure
    for i in range(0, len(x_data), 1):
        fig.add_trace(
            go.Scatter(
                x=x_data[i],
                y=y_data[i],
                name=line_name[i],
                yaxis=y[i],
                line={"color": line_color[i], "dash": line_styles[i]},
            )
        )

    # Create Layout for the Html

    fig.update_layout(
        title=go.layout.Title(text=title, xref="paper", x=0.5),
        xaxis=go.layout.XAxis(
            title=go.layout.xaxis.Title(
                text=x_title,
            ),
            rangeslider={"visible": True},
        ),
    )

    fig.update_layout(
        xaxis={"domain": [0.05, 0.95]},
        yaxis={"title": {"text": "Power (kW)"}},
        yaxis2={"title": {"text": "Hydrogen Produced (kg/h)"}, "overlaying": "y", "side": "right"},
        yaxis3={
            "title": {"text": "yaxis3 title"},
            "anchor": "free",
            "overlaying": "y",
            "autoshift": True,
        },
        yaxis4={
            "title": {"text": "yaxis4 title"},
            "anchor": "free",
            "overlaying": "y",
            "autoshift": True,
        },
    )

    fig.write_html((filename + ".html"), include_mathjax="cdn")
    # fig.write_image(filename + '.svg')
    # fig.write_image(filename + '.pdf')
    if fig_show:
        fig.show()

In [22]:
# os.chdir(r"C:\Users\MIKKDM\Documents\H2Integrate\NucH2INtegrate\examples\99_nuclear_reactor_htse")

x_title = "Time"
y_title = ["Power (MW)", "Hydrogen Produced (kg/h)"]
line_name = ["Electricity Out", "Hydrogen Produced"]
line_color = ["deepskyblue", "red"]
line_styles = ["solid", "dash"]
x_data = [np.arange(8760)] * 2
y_data = [nuclear_elec_out, electrolyzer_h2_out]
title = "Nuclear Reactor Optimization Output"
filename = "nuclear_example_output"
y = ["y1", "y2"]
plot_graph(
    x_data,
    y_data,
    line_name,
    title,
    x_title,
    y_title,
    filename,
    line_color,
    y,
    line_styles,
    fig_show=True,
)